In [28]:
from woww.api.erddap import WOWWErdappData
from datetime import datetime, timedelta

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [2]:
wd = WOWWErdappData(server="https://pae-paha.pacioos.hawaii.edu/erddap/",
                    protocol="griddap",
                    dataset_id="ww3_global",
                    initialize=True)

In [56]:
wd.set_vars_constraints(variables=['Tdir', 'Tper', 'Thgt',
                                    'sdir','sper','shgt',
                                    'wdir','wper','whgt'],
                        longitude=115,#(305,333),
                        latitude=-31,#(-35,4),
                        start_date=(datetime.now()-timedelta(days=1)).strftime("%Y-%m-%dT%H:%M:%SZ"),
                        correct_pos=False)

ww3 = wd.grab_batch_data(response_type="pandas")

In [57]:
#TRANSFORM
ww3 = wd.process_var_labels(ww3)
ww3 = wd.rename_var_labels(ww3)

In [58]:
ww3['tdir_windrose'] = wd.get_direc_quadrant(data=ww3,direc_var='tdir')
ww3['sdir_windrose'] = wd.get_direc_quadrant(data=ww3,direc_var='sdir')
ww3['wdir_windrose'] = wd.get_direc_quadrant(data=ww3,direc_var='wdir')

,date_time,depth,latitude,longitude,tdir,tper,thgt,sdir,sper,shgt,wdir,wper,whgt,tdir_windrose,sdir_windrose,wdir_windrose
0,2025-05-03T20:00:00Z,0.0,-31.0,115.0,221.0,16.949152,5.73,223.0,16.869999,5.73,NaN,NaN,NaN,SW,SW,NaN
1,2025-05-03T21:00:00Z,0.0,-31.0,115.0,221.0,16.949152,5.69,223.0,16.840000,5.69,NaN,NaN,NaN,SW,SW,NaN
2,2025-05-03T22:00:00Z,0.0,-31.0,115.0,221.0,16.666666,5.63,223.0,16.800000,5.63,NaN,NaN,NaN,SW,SW,NaN
3,2025-05-03T23:00:00Z,0.0,-31.0,115.0,221.0,16.666666,5.55,223.0,16.740000,5.55,NaN,NaN,NaN,SW,SW,NaN
4,2025-05-04T00:00:00Z,0.0,-31.0,115.0,221.0,16.666666,5.47,223.0,16.680000,5.47,NaN,NaN,NaN,SW,SW,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,2025-05-10T14:00:00Z,0.0,-31.0,115.0,240.0,15.151515,2.52,233.0,15.219999,2.51,NaN,NaN,NaN,WSW,SW,NaN
163,2025-05-10T15:00:00Z,0.0,-31.0,115.0,239.0,15.151515,2.60,232.0,15.099999,2.59,NaN,NaN,NaN,WSW,SW,NaN
164,2025-05-10T16:00:00Z,0.0,-31.0,115.0,240.0,14.925373,2.68,232.0,14.910000,2.67,NaN,NaN,NaN,WSW,SW,NaN
165,2025-05-10T17:00:00Z,0.0,-31.0,115.0,240.0,14.705881,2.74,232.0,14.730000,2.73,NaN,NaN,NaN,WSW,SW,NaN
166,2025-05-10T18:00:00Z,0.0,-31.0,115.0,239.0,14.492752,2.79,237.0,14.589999,2.37,213.0,6.65,1.44,WSW,WSW,SSW

In [48]:
wd2 = WOWWErdappData(server="https://pae-paha.pacioos.hawaii.edu/erddap/",
            protocol="griddap",
            dataset_id="ncep_global")

In [60]:
wd2.set_vars_constraints(variables=['ugrd10m', 'vgrd10m'],
                        longitude=115,
                        latitude=-31,
                start_date=(datetime.now()-timedelta(days=1)).strftime("%Y-%m-%dT%H:%M:%SZ"),
                correct_pos=False)

gfs = wd2.grab_batch_data(response_type="pandas")

gfs = wd2.process_var_labels(gfs)
gfs = wd2.rename_var_labels(gfs)
gfs = wd2.select_vars(gfs)
gfs['wspd'] = wd2.calc_wind_veloc(gfs)
gfs['wdir'] = wd2.calc_wind_direc(gfs)

In [61]:
gfs

,date_time,latitude,longitude,uw,vw,wspd,wdir
0,2025-05-03T21:00:00Z,-31.0,115.0,5.828696,2.817537,6.473964,25.798683
1,2025-05-04T00:00:00Z,-31.0,115.0,4.720684,2.548303,5.364578,28.360907
2,2025-05-04T03:00:00Z,-31.0,115.0,5.165671,3.857940,6.447314,36.753915
3,2025-05-04T06:00:00Z,-31.0,115.0,4.390771,2.916438,5.271099,33.592905
4,2025-05-04T09:00:00Z,-31.0,115.0,3.676077,3.188086,4.865946,40.933538
...,...,...,...,...,...,...,...
57,2025-05-11T00:00:00Z,-31.0,115.0,-1.943865,3.028906,3.599011,122.691180
58,2025-05-11T03:00:00Z,-31.0,115.0,-1.130640,2.871352,3.085938,111.492812
59,2025-05-11T06:00:00Z,-31.0,115.0,-0.482085,6.144761,6.163642,94.485931
60,2025-05-11T09:00:00Z,-31.0,115.0,-1.325876,8.146154,8.253349,99.244457
61,2025-05-11T12:00:00Z,-31.0,115.0,-3.930173,6.884468,7.927304,119.720983